import type { BookingRecord, Service, StaffMember } from '../../types/booking';

export const mockStaff: StaffMember[] = [
  {
    id: 'st-1',
    name: 'Elena Rostova',
    role: 'BARBER',
    specialization: 'Senior Colorist',
  },
  {
    id: 'st-2',
    name: 'Marta Kowalska',
    role: 'BARBER',
    specialization: 'Hair Stylist & Cut',
  },
  {
    id: 'st-3',
    name: 'Piotr Zieliński',
    role: 'BARBER',
    specialization: 'Master Barber',
  },
  {
    id: 'st-4',
    name: 'Julia Nowak',
    role: 'BARBER',
    specialization: 'Scalp & Hair Rituals',
  },
];

export const mockServices: Service[] = [
  {
    id: 'srv-1',
    name: 'Balayage & Modelowanie',
    durationMin: 150,
    price: 380,
    category: 'Koloryzacja',
    description: 'Multi-dimensional brush lightening with customized toning and blowout finish.',
  },
  {
    id: 'srv-2',
    name: 'Strzyżenie Autorskie Damskie',
    durationMin: 60,
    price: 190,
    category: 'Strzyżenie',
    description: 'Signature tailored haircut crafted to facial geometry and natural hair texture.',
  },
  {
    id: 'srv-3',
    name: 'Strzyżenie Męskie & Trymowanie Brody',
    durationMin: 50,
    price: 140,
    category: 'Barbering',
    description: 'Classic precision cut, straight-razor contouring, and nourishing argan oil grooming.',
  },
  {
    id: 'srv-4',
    name: 'Rytuał Odbudowy Keratynowej',
    durationMin: 75,
    price: 240,
    category: 'Pielęgnacja',
    description: 'Deep keratin reconstructive treatment for damaged hair with therapeutic steam hydration.',
  },
  {
    id: 'srv-5',
    name: 'Tonowanie & Regeneracja Połysku',
    durationMin: 60,
    price: 180,
    category: 'Koloryzacja',
    description: 'Shade refresh, cuticle sealing, and high-gloss mirror shine finish.',
  },
  {
    id: 'srv-6',
    name: 'Rytuał Oczyszczający Scalp Detox',
    durationMin: 45,
    price: 160,
    category: 'Pielęgnacja',
    description: 'Scalp acid exfoliation treatment paired with lymphatic drainage massage.',
  },
];

export const mockBookings: BookingRecord[] = [
  {
    id: 'BK-101',
    barberId: 'st-1',
    clientId: 'cl-1',
    serviceId: 'srv-1',
    clientName: 'Aleksandra Wiśniewska',
    clientPhone: '+48 512 890 234',
    clientEmail: 'aleksandra.w@example.com',
    serviceName: 'Balayage & Modelowanie',
    masterName: 'Elena Rostova',
    startTime: '09:30',
    endTime: '12:00',
    price: '380 zł',
    status: 'CONFIRMED',
    notes: 'Wrażliwa skóra głowy. Używać produktów bez amoniaku.',
    startMinute: 570,
    durationMinutes: 150,
  },
  {
    id: 'BK-102',
    barberId: 'st-1',
    clientId: 'cl-2',
    serviceId: 'srv-5',
    clientName: 'Karolina Dąbrowska',
    clientPhone: '+48 601 223 344',
    clientEmail: 'karolina.d@example.com',
    serviceName: 'Tonowanie & Regeneracja',
    masterName: 'Elena Rostova',
    startTime: '13:00',
    endTime: '14:00',
    price: '180 zł',
    status: 'CONFIRMED',
    notes: 'Chłodny odcień beżu.',
    startMinute: 780,
    durationMinutes: 60,
  },
  {
    id: 'BK-103',
    barberId: 'st-2',
    clientId: 'cl-3',
    serviceId: 'srv-2',
    clientName: 'Zofia Kamińska',
    clientPhone: '+48 503 911 022',
    clientEmail: 'zofia.k@example.com',
    serviceName: 'Strzyżenie Autorskie Damskie',
    masterName: 'Marta Kowalska',
    startTime: '08:30',
    endTime: '09:30',
    price: '190 zł',
    status: 'CONFIRMED',
    startMinute: 510,
    durationMinutes: 60,
  },
  {
    id: 'BK-104',
    barberId: 'st-2',
    clientId: 'cl-4',
    serviceId: 'srv-4',
    clientName: 'Monika Lewandowska',
    clientPhone: '+48 792 445 109',
    clientEmail: 'monika.l@example.com',
    serviceName: 'Rytuał Odbudowy Keratynowej',
    masterName: 'Marta Kowalska',
    startTime: '10:15',
    endTime: '11:30',
    price: '240 zł',
    status: 'PENDING',
    notes: 'Klientka spóźni się około 5 minut.',
    startMinute: 615,
    durationMinutes: 75,
  },
  {
    id: 'BK-105',
    barberId: 'st-2',
    clientId: 'cl-5',
    serviceId: 'srv-2',
    clientName: 'Anna Wójcik',
    clientPhone: '+48 609 881 230',
    serviceName: 'Strzyżenie Autorskie Damskie',
    masterName: 'Marta Kowalska',
    startTime: '14:00',
    endTime: '15:00',
    price: '190 zł',
    status: 'CONFIRMED',
    startMinute: 840,
    durationMinutes: 60,
  },
  {
    id: 'BK-106',
    barberId: 'st-3',
    clientId: 'cl-6',
    serviceId: 'srv-3',
    clientName: 'Tomasz Majewski',
    clientPhone: '+48 518 700 892',
    clientEmail: 'tomasz.m@example.com',
    serviceName: 'Strzyżenie Męskie & Brody',
    masterName: 'Piotr Zieliński',
    startTime: '09:00',
    endTime: '09:50',
    price: '140 zł',
    status: 'CONFIRMED',
    startMinute: 540,
    durationMinutes: 50,
  },
  {
    id: 'BK-107',
    barberId: 'st-3',
    clientId: 'cl-7',
    serviceId: 'srv-3',
    clientName: 'Michał Kozłowski',
    clientPhone: '+48 504 112 998',
    serviceName: 'Strzyżenie Męskie & Brody',
    masterName: 'Piotr Zieliński',
    startTime: '11:00',
    endTime: '11:50',
    price: '140 zł',
    status: 'CANCELLED',
    notes: 'Odwołano telefonicznie o 8:15.',
    startMinute: 660,
    durationMinutes: 50,
  },
  {
    id: 'BK-108',
    barberId: 'st-3',
    clientId: 'cl-8',
    serviceId: 'srv-3',
    clientName: 'Jakub Szymański',
    clientPhone: '+48 602 331 445',
    serviceName: 'Strzyżenie Męskie & Brody',
    masterName: 'Piotr Zieliński',
    startTime: '12:30',
    endTime: '13:20',
    price: '140 zł',
    status: 'CONFIRMED',
    startMinute: 750,
    durationMinutes: 50,
  },
  {
    id: 'BK-109',
    barberId: 'st-4',
    clientId: 'cl-9',
    serviceId: 'srv-6',
    clientName: 'Patrycja Kaczmarek',
    clientPhone: '+48 515 901 623',
    serviceName: 'Scalp Detox & Masaż',
    masterName: 'Julia Nowak',
    startTime: '10:00',
    endTime: '10:45',
    price: '160 zł',
    status: 'CONFIRMED',
    startMinute: 600,
    durationMinutes: 45,
  },
  {
    id: 'BK-110',
    barberId: 'st-4',
    clientId: 'cl-10',
    serviceId: 'srv-4',
    clientName: 'Ewa Grabowska',
    clientPhone: '+48 731 229 004',
    serviceName: 'Rytuał Odbudowy Keratynowej',
    masterName: 'Julia Nowak',
    startTime: '12:00',
    endTime: '13:15',
    price: '240 zł',
    status: 'CONFIRMED',
    startMinute: 720,
    durationMinutes: 75,
  },
];
